[build]
  command = "npm run build"
  publish = "public"

# Environment settings
[build.environment]
  NODE_VERSION = "18.12.0"

# Required for Gatsby sites
[[plugins]]
  package = "@netlify/plugin-gatsby"